### ISSUE TITLE
Disappearing bottles 

### ISSUE THREAD

**Issue by vvandenschrieck** [CSITEd/ILPADS#2]
![capture d ecran 2015-03-01 a 22 12 21](https://cloud.githubusercontent.com/assets/1985444/6432851/4d3ff918-c060-11e4-87fb-a24ae7e08c7b.png)

Strange issue with the first activity : In this scenario, after a first sort using the scale, I tried to re-weight some of them and they ended up going back in the zone above the scale.  Three bottles did it, and so are they stacked one on top of the other, the last one hidding the others.

**Comment by combefis** [comment]
We managed to reproduce the bug, we are working on a way to handle it!

**Comment by nhysi** [comment]
I fix this in the pull request that i'll do this afternoon.

**Comment by combefis** [comment]
The pull request has been accepted and fixes this issue.
